PersonalWeblog/Areas/Admin/Controllers/AdminController.cs
using Application_Contracts.Application_Blog;
using Application_Contracts.Application_Comment;
using Microsoft.AspNetCore.Mvc;

namespace PersonalWeblog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminController : Controller
    {
        private readonly IBlogApplication _blogApplication;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IApplicationComments _applicationComments;
        public AdminController(IBlogApplication blogApplication, IWebHostEnvironment hostEnvironment, IApplicationComments applicationComments)
        {
            _blogApplication = blogApplication;
            _hostingEnvironment = hostEnvironment;
            _applicationComments = applicationComments;
        }
        public IActionResult Index()
        {
            return View(_blogApplication.GetBlogsForDemonstrate());
        }
        [HttpGet]
        public IActionResult CreateBlog()
        {
            var addBlogCommand = new CreateBlogCommand();
            return View(addBlogCommand);
        }
        [HttpPost]
        public IActionResult CreateBlog(IFormFile image, CreateBlogCommand command)
        {
            command.ImageAddress = UpsertImage(image);
            _blogApplication.CreateBlog(command);
            return Redirect("Index");
        }
        [HttpGet]
        public IActionResult UpdateBlog(int blogId)
        {
            var blog = _blogApplication.GetBlog(blogId, true);
            return View(blog);
        }
        [HttpPost]
        public IActionResult UpdateBlog(IFormFile? image, UpdateBlogCommand command)
        {
            if (image != null)
            {
                if (command.ImageAddress != null)
                {
                    var rootPath = _hostingEnvironment.WebRootPath;
                    var oldPic = Path.Combine(rootPath, command.ImageAddress.TrimStart('\\'));
                    if (System.IO.File.Exists(oldPic))
                    {
                        System.IO.File.Delete(oldPic);
                    }
                }
                var newImageAddress = UpsertImage(image);
                command.ImageAddress = newImageAddress;
            }
            _blogApplication.UpdateBlog(command);
            return Redirect("Index");
        }
        public IActionResult DeleteBlog(int blogId)
        {
            _blogApplication.DeleteBlog(blogId);
            return Redirect("Index");
        }
        public IActionResult ActivateBlog(int blogid)
        {
            _blogApplication.ActivateBlog(blogid);
            return Redirect("Index");
        }
        [HttpGet]
        public IActionResult GetComments()
        {
            var comments = _applicationComments.GetAllComments();
            return View(comments);
        }
        public IActionResult ChangeStatus(int commentId,Domain.StatusCode code)
        {
            _applicationComments.ChangeStatusCode(commentId,code);
            return Redirect("GetComments");
        }
        private string UpsertImage(IFormFile image)
        {
            var rootPath = _hostingEnvironment.WebRootPath;
            var filename = Guid.NewGuid().ToString();
            var uploadPath = Path.Combine(rootPath, @"images\Blogs");
            var extension = Path.GetExtension(image.FileName);
            using (var stream = new FileStream(Path.Combine(uploadPath, filename + extension), FileMode.Create))
            {
                image.CopyTo(stream);
            }
            var imageAddress = "images/Blogs/" + filename + extension;
            return imageAddress;
        }

    }
}

PersonalWeblog/Areas/Main/Controllers/HomeController.cs
using Application_Contracts.Application_Blog;
using Application_Contracts.Application_Comment;
using Domain.BlogAgg;
using Domain.UserAgg;
using Infrastructure;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mime;

namespace PersonalWeblog.Main.Controllers
{
    [Area("Main")]
    public class HomeController : Controller
    {
        #region Services
        private Context _context;
        private IBlogApplication _blogServices;
        private IWebHostEnvironment _webHostEnvironment;
        private IApplicationComments _applicationComments;
        public HomeController(Context context
       , IBlogApplication blogServices
       , IWebHostEnvironment webHostEnvironment
       , IApplicationComments applicationComments)
        {
            _context = context;
            _blogServices = blogServices;
            _webHostEnvironment = webHostEnvironment;
            _applicationComments = applicationComments;
        }
        #endregion
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ArticleDownload(int blogId)
        {
            var blog = _blogServices.GetBlog(blogId);
            var rootpath = _webHostEnvironment.WebRootPath;
            var filename = "\\"+Guid.NewGuid().ToString();
            using (var stream = new StreamWriter(_webHostEnvironment.WebRootPath + $"{filename}.txt", true, encoding: System.Text.Encoding.UTF8))
            {
                stream.WriteLine(blog.BlogTitle);
                stream.Write(blog.BlogBody);
            }

            var byteslice = System.IO.File.ReadAllBytes(rootpath+filename+".txt");
            string fullname = filename+".txt";
            return File(byteslice, MediaTypeNames.Text.RichText, fullname);
        }
        public IActionResult ViewBlogDetail(int blogId)
        {
            var blog = _blogServices.GetBlog(blogId);
            return View(blog);
        }
        [HttpPost]
        public IActionResult AddComment(AddCommentCommand command)
        {
            _applicationComments.AddComment(command);
            return Redirect($"ViewBlogDetail?blogId={command.blogId}");
        }

    }
}

PersonalWeblog/Areas/Main/ViewComponents/BlogCommentsViewComponent.cs
using Application_Contracts.Application_Comment;
using Microsoft.AspNetCore.Mvc;

namespace PersonalWeblog.Areas.Main.ViewComponents
{
    public class BlogCommentsViewComponent : ViewComponent
    {
        private readonly IApplicationComments _services;
        public BlogCommentsViewComponent(IApplicationComments services)
        {
            _services = services;
        }

        public IViewComponentResult Invoke(int blogId)
        {
            var comments = _services.GetBlogComments(blogId);
            return View("_Comments", comments);
        }

    }
}

PersonalWeblog/Areas/Main/ViewComponents/BlogViewComponent.cs
using Application_Contracts.Application_Blog;
using Microsoft.AspNetCore.Mvc;

namespace PersonalWeblog.Main.ViewComponents;

public class BlogViewComponent : ViewComponent
{
    private IBlogApplication _iblogservices;
    public BlogViewComponent(IBlogApplication iblogservices)
    {
        _iblogservices = iblogservices;
    }
    public IViewComponentResult Invoke()
    {
        var blogs = _iblogservices.GetAllBlogs().Take(6).ToList();
        return View("_Blog", blogs);
    }
}

PersonalWeblog/Areas/Admin/Views/Admin/CreateBlog.cshtml
@model Application_Contracts.Application_Blog.CreateBlogCommand
@{
    ViewData["Title"] = "Create Blog";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<body>
    <div class="container mt-4">
        <h2 class="text-center">Create a New Blog Post</h2>
        <form action="CreateBlog" method="POST" enctype="multipart/form-data">
            <div class="form-group">
                <input type="text" class="form-control" asp-for="@Model.BlogTitle" placeholder="Title" required>
            </div>
            <div class="form-group">
                <textarea class="form-control" asp-for="@Model.BlogDescrioption" placeholder="Description" rows="3" required></textarea>
            </div>
            <div class="form-group">
                <textarea class="form-control" asp-for="@Model.BlogBody" placeholder="Body" rows="6" required></textarea>
            </div>
            <div class="form-group">
                <input required name="image" type="file" accept="image/*">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" asp-for="@Model.ImageTitle" placeholder="Image Title" required>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" asp-for="@Model.AltText" placeholder="Image Alt Text" required>
            </div> 
            <div class="form-group">
                <input type="email" class="form-control" asp-for="@Model.Email" placeholder="Your email" required>
            </div> 
            <div class="form-group">
                <input type="text" class="form-control" asp-for="@Model.Fullname" placeholder="enter your fullname" required>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Submit</button>
        </form>
    </div>
</body>

PersonalWeblog/Areas/Admin/Views/Admin/GetComments.cshtml
@using Application_Contracts.Application_Comment;
@model List<CommentViewModel>
@{
    ViewData["Title"] = "GetComments";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 class="mt-4">Blogs dashboard</h2>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Content</th>
                <th>Blog title</th>
                <th>Author id</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var comment in Model)
            {
                <tr>
                    <td>@comment.blogId</td>
                    <td>@comment.Content</td>
                    <td>@comment.BlogTitle</td>
                    <td>@comment.userId</td>
                    <td>
                        @if (comment.Status == (int)Domain.StatusCode.Confirmed)
                        {
                            <i class="bi bi-check-circle-fill"></i>
                        }
                        else if (comment.Status == (int)Domain.StatusCode.Checking)
                        {
                            <i class="bi bi-envelope-exclamation-fill"></i>
                        }
                        else
                        {
                            <i class="bi bi-x-circle-fill"></i>
                        }
                    </td>
                    <td>
                        @if (comment.Status == (int)Domain.StatusCode.Confirmed)
                        {
                            <a asp-action="ChangeStatus" asp-route-commentId="@comment.Id" asp-route-code="@Domain.StatusCode.Canseled" style="margin-right:10px;" class="btn btn-danger">Cansel</a>
                        }
                        else if (comment.Status == (int)Domain.StatusCode.Checking)
                        {
                            <a asp-action="ChangeStatus" asp-route-commentId="@comment.Id" asp-route-code="@Domain.StatusCode.Canseled" style="margin-right:10px;" class="btn btn-danger">Cansel</a>
                            <a asp-action="ChangeStatus" asp-route-commentId="@comment.Id" asp-route-code="@Domain.StatusCode.Confirmed" style="margin-right:10px;" class="btn btn-success">Confirm</a>
                        }
                        else
                        {
                            <a asp-action="ChangeStatus" asp-route-commentId="@comment.Id" asp-route-code="@Domain.StatusCode.Confirmed" style="margin-right:10px;" class="btn btn-success">Confirm</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

PersonalWeblog/Areas/Admin/Views/Admin/Index.cshtml
@model List<Application_Contracts.Application_Blog.BlogDemonstrateAdmin>
@{
    ViewData["Title"] = "Admin section";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2 class="mt-4">Blogs dashboard</h2>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Blog id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Author id</th>
                <th>Is delete</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var blog in Model)
            {
                <tr>
                    <td>@blog.blogId</td>
                    <td>@blog.title</td>
                    <td>@blog.desctiption</td>
                    <td>@blog.authorId</td>
                    <td>
                        @if (blog.isDelete)
                        {
                            <i class="bi bi-check"></i>
                        }
                        else
                        {
                            <i class="bi bi-x-lg"></i>
                        }
                    </td>
                    <td>
                        @if (!blog.isDelete)
                        {
                            <a asp-action="DeleteBlog" asp-route-blogId="@blog.blogId" style="margin-right:10px;" class="btn btn-danger">Delete</a>
                        }
                        else
                        {
                            <a asp-action="ActivateBlog" asp-route-blogId="@blog.blogId" style="margin-right:10px;" class="btn btn-success">Activate</a>
                        }
                        <a asp-action="UpdateBlog" asp-route-blogId="@blog.blogId" style="margin-right:10px;" class="btn btn-primary">Edit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

PersonalWeblog/Areas/Admin/Views/Admin/UpdateBlog.cshtml
@model Application_Contracts.Application_Blog.UpdateBlogCommand
@{
    ViewData["Title"] = "Update blog";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<body>
    <div class="container mt-4">
        <h2 class="text-center">Create a New Blog Post</h2>
        <form action="UpdateBlog" method="POST" enctype="multipart/form-data">
            <input type="hidden" asp-for="@Model.Id" value="@Model.Id" />
            <input type="hidden" asp-for="@Model.ImageAddress" value="@Model.ImageAddress" />
            <div class="form-group">
                <input type="text" class="form-control" asp-for="@Model.BlogTitle" placeholder="Title" required>
            </div>
            <div class="form-group">
                <textarea class="form-control" asp-for="@Model.BlogDescrioption" placeholder="Description" rows="3" required></textarea>
            </div>
            <div class="form-group">
                <textarea class="form-control" asp-for="@Model.BlogBody" placeholder="Body" rows="6" required></textarea>
            </div>
            <div class="form-group">
            <input type="file" class="form-control-file" name="image" accept="image/*" required>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" asp-for="@Model.ImageTitle" placeholder="Image Title" required>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" asp-for="@Model.AltText" placeholder="Image Alt Text" required>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Submit</button>
        </form>
    </div>
</body>

PersonalWeblog/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PersonalWeblog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PersonalWeblog.styles.css" asp-append-version="true" />
</head>
<body dir="rtl">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="btn btn-light" asp-area="/Main" asp-controller="Home" asp-action="Index">Main page</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Admin" asp-action="CreateBlog">Add new blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Admin" asp-action="GetComments">Comments managment</a>
                        </li>
                        <li class="nav-item">
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script type="text/javascript" src="@Url.Action("MyJs","Home",new {area = "Main"})>"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PersonalWeblog/Areas/Main/Views/Home/Components/Blog/_Blog.cshtml
@model List<Application_Contracts.Application_Blog.BlogViewModel>
@if (Model.Count != 0)
{
    @foreach (var blog in Model)
    {
        <div class="col-md-4">
            <a asp-controller="Home" asp-action="ViewBlogDetail" asp-route-blogId="@blog.Id">
                <div class="post-content">
                    <figure>
                        <img src="~/@blog.ImageAddress" alt="@blog.AltText">
                        <figcaption class="hover-fig">
                            <i class="fa fa-plus"></i>
                        </figcaption>
                        <figcaption class="date-fig">
                            <span>@blog.CreationDate</span>
                            <i class="fa fa-date"></i>
                        </figcaption>
                    </figure>
                    <p>@blog.BlogDescrioption</p>
                    <a href="@Url.Action("ArticleDownload","Home",new{area ="Main" , blogId = blog.Id})">دانلود</a>
                </div>
            </a>
        </div>
    }
}

PersonalWeblog/Areas/Main/Views/Home/Components/BlogComments/_Comments.cshtml
@using Application_Contracts.Application_Comment;
@model List<CommentDemonstrationViewModel>
@foreach (var comment in Model)
{
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">نام نویسنده:<strong>@comment.AuthorName</strong></h5>
            <p class="card-text">@comment.Content</p>
        </div>
    </div>
    <hr />
}

PersonalWeblog/Areas/Main/Views/Home/Index.cshtml
@{
    
    ViewData["Title"] = "Cart";
    Layout = "~/Areas/Main/Views/Shared/_Layout.cshtml";
}
<body>
 
    <div class="col-md-9">
        <div class="col-md-12">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active">
                        <figure>
                            <img src="img/slide/Slide1.jpg" alt="">
                            <figcaption></figcaption>
                        </figure>
                        <div class="carousel-caption">
                            <h3>طراحی وب</h3>
                            <p>طراحی وب رو از همین امروز شروع کن</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @await Component.InvokeAsync("Blog")
    </div>
    <script type="text/javascript" src="@Url.Action("MyJs","Home",new {area = "Main"})"></script>
</body>

PersonalWeblog/Areas/Main/Views/Home/ViewBlogDetail.cshtml
@model Application_Contracts.Application_Blog.BlogViewModel
@{
    ViewData["Title"] = "Blog Details";
    Layout = "~/Areas/Main/Views/Shared/_Layout.cshtml";
}
<div class="col-md-9">
    <div class="col-md-12">
        <div class="single-content">
            <div class="single-img">
                <img src="~/@Model.ImageAddress" alt="@Model.AltText">
            </div>
            <div class="single-title">
                <h1>@Model.BlogTitle</h1>
            </div>
            <p>@Model.BlogBody</p>
            <hr>
            <div class="comment">
                <span><i class="fa fa-comments"></i>نظری برای این مطلب بنویسید</span>
                <form action="AddComment" method="post">
                    <div class="form-group col-md-6">
                        <input class="form-control" type="text" name="Fullname" id="Fullname" placeholder="نام خود را وارد کنید">
                    </div>
                    <div class="form-group col-md-6">
                        <input class="form-control" type="email" name="Email" id="Email" placeholder="ایمیل را واردکنید">
                    </div>
                    <div class="form-group col-md-12">
                        <textarea class="form-control" name="Content" id="Content" placeholder="متن نظر" rows="7"></textarea>
                    </div>
                    <div class="form-group col-md-12">
                        <button class="btn btn-default" type="submit">ارسال نظر</button>
                    </div>
                    <input type="hidden" name="blogId" value="@Model.Id" id="blogId" />
                </form>
            </div>
            <div class="comments-note">
                نظرات این مقاله
                @await Component.InvokeAsync("BlogComments",Model.Id)
            </div>
        </div>
    </div>
</div>
<br>
<br>

PersonalWeblog/Areas/Main/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PersonalWeblog</title>
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/font-awesome.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link href='https://cdn.fontcdn.ir/Font/Persian/Vazir/Vazir.css' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PersonalWeblog.styles.css" asp-append-version="true" />
</head>
<body dir="rtl">
    <header>
        <div class="main-menu">
            <div class="container">
                <ul>
                    <li><a asp-controller="Home" asp-action="Index">صفحه اصلی</a></li>
                    <li><a href="https://github.com/BigMasoud22">تماس</a></li>
                    <li><a href="https://github.com/BigMasoud22">درباره</a></li>
                </ul>
            </div>
        </div>
        <div class="top-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-2">
                        <img src="img/logo.png" alt="" class="logo">
                    </div>
                    <div class="col-md-5">
                        <div class="index-h1">
                            <h1>بهترین و متفاوت ترین مقالات آموزشی</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
      
    </header>
    <div class="col-md-3" style="margin-left:20px;">
        <div class="sidebar">
            <div class="sidebar-text">
                <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. </p>
            </div>
            <div class="sidebar-social">
                <ul>
                    <li>
                        <a href="#" class="telegram"><i class="fa fa-send"></i>دنبال کردن در تلگرام</a>
                    </li>
                    <li>
                        <a href="#" class="twitter"><i class="fa fa-twitter"></i>صفحه توئیتر ما</a>
                    </li>
                    <li>
                        <a href="#" class="aparat"><i class="fa fa-video-camera"></i>دنبال کردن در آپارات</a>
                    </li>
                    <li>
                        <a href="#" class="youtube"><i class="fa fa-youtube"></i>کانال یوتیوب</a>
                    </li>
                    <li>
                        <a href="#" class="instagram"><i class="fa fa-instagram"></i>پیج اینستاگرام </a>
                    </li>
                </ul>
            </div>
            <div class="category-sidebar">
                <span><i class="fa fa-bookmark"></i>دسته بندی مطالب</span>
                <ul>
                    <li><a href="#">دنبال کردن در تلگرام</a></li>
                    <li><a href="#">صفحه توئیتر ما</a></li>
                    <li><a href="#">دنبال کردن در آپارات</a></li>
                    <li><a href="#">کانال یوتیوب</a></li>
                    <li><a href="#">پیج اینستاگرام</a></li>
                </ul>
            </div>
            <div class="category-sidebar ads-sidebar">
                <span><i class="fa fa-slack"></i>تبلیغات</span>
                <ul>
                    <li>
                        <a title="link" href="#">
                            <figure>
                                <img src="~/images/ads/ads1.jpg" alt="">
                                <figcaption></figcaption>
                            </figure>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div style="margin-top:50px;padding-bottom:10%;" class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="footer-contact">
                            <span class="footer-title">چگونه با ما در تماس باشید</span>
                            <ul>
                                <li><a href="#" title="تهران" data-toggle="tooltip"><i class="fa fa-map-marker"></i></a></li>
                                <li><a href="#" title="mwsoush.84@gmail.com" data-toggle="tooltip"><i class="fa fa-envelope-o"></i></a></li>
                                <li><a href="#" title="09352604271" data-toggle="tooltip"><i class="fa fa-mobile"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script type="text/javascript" src="@Url.Action("MyJs","Home",new {area = "Main"})>"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>